spring:
  profiles:
    include: db,dao,redis
  datasource:
    db1:
        url: jdbc:mysql://127.0.0.1:3306/test01?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver


    db2:
        url: jdbc:mysql://127.0.0.1:3306/test02?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

